### ISSUE TITLE
Fallback to Vagrant's ansible_local provisioner

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/basic-wordpress-vagrant#28]
For Windows and possible Ansible-less Mac/Linux boxes, try Vagrant's [`ansible_local`](https://www.vagrantup.com/docs/provisioning/ansible_local.html) provisioner instead of the shell fallback. 

Also test speed vs running Ansible from the controller vs locally on the Vagrant box.

Ansible has been installed on our base box since https://github.com/ideasonpurpose/basic-wordpress-box/commit/b6330d119d77f4909134742b0c29c97c1777e31a but I should probably check the version...

**Comment by joemaller** [comment]
Thinking it might be a better solution to Ansible's currently messed up unarchive module to just move everything onto the local box. I'd prefer not to lose the download caching, and it'll probably be slower, but dropping a dependency is probably worth it. Asking users to install specific versions is embarrassing.

**Comment by joemaller** [comment]
Just for the record, on-VM disk access in the shared folder is at least 10x slower. One of the nice things about this project is how fast activation and spin-ups are. I don't want to lose that.

**Comment by The4thLaw** [comment]
My 2 cents :)

If you want to keep the recommentation to use Ansible on the host, that's fine. It makes complete sense.
But since it also works without it (I just commented the lines in the Vagrantfile), you should document it as well, and explain the pros and cons.

Running Ansible inside the VM is good enough for me, and I think it would be good enough for other users as well :)

**Comment by joemaller** [comment]
Switching. It's actually faster. Thanks @The4thLaw !
