### ISSUE TITLE
Add path to ~/.wp-cli/config.yml

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-vagrant#30]
I may be still using an old version of this repo, but it would be nice to include the `path` in `~/.wp-cli/config.yml` so you can type `wp` from anywhere after `vagrant ssh`.
## ~/.wp-cli/config.yml

`path: /var/www/wordpress/`

**Comment by joemaller** [comment]
Excellent point. I'll get that in there this week.

**Comment by jgraup** [comment]
Sweet!

**Comment by joemaller** [comment]
Turns out that was already there! Added to the base box back last November: https://github.com/ideasonpurpose/basic-wordpress-box/commit/1227debb001cd5e5b2126b7c4873a80f633934d0

It's using `/vagrant/site` as the path instead of the symlinked `/var/www/wordpress`, but it works  the same.

If you upgrade now, please see the note in the [Readme](https://github.com/ideasonpurpose/basic-wordpress-vagrant/blob/d15e1d13072004ab865a4234a5cd0e06ab8ef0e1/README.md#bug--vagrant-185-is-broken-use-vagrant-184-bug) about problems with Vagrant 1.8.5 and VirtualBox 5.1. Should be resolved soon, but for now we need to hold off on using the latest releases.
